Controllers/BookController.cs
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Knigosha.Core.Models;
using Knigosha.Core.Models.Enums;
using Knigosha.Core.ViewModels;
using Knigosha.Core.ViewModels.BookViewModels;
using Knigosha.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Knigosha.Controllers
{
    public class BookController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BookController(ApplicationDbContext context,
            IHostingEnvironment environment,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _hostingEnvironment = environment;
            _context = context;
        }

        public int CurrentPage { get; set; } = 1;

        public int Count { get; set; }

        public int PageSize { get; set; } = 24;

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));

        public bool EnablePrevious => CurrentPage > 1;

        public bool EnableNext => CurrentPage < TotalPages;


        public async Task<IActionResult> IndexAdmin()
        {
            return View(await _context.Books.ToListAsync());
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(string keywords, string bookPublisher, BookCategories category, AgeGroups ageGroup, string yearFrom, string yearTo, string sortField, int page = 1)
        {
            var user = await _userManager.GetUserAsync(User);

            var books = _context.Books
                .Include(b => b.Answers)
                .Include(b => b.BookRatings)
                .AsQueryable();

            CurrentPage = page == 0 ? 1 : page;

            var publishers = books.Select(b => b.Publisher);

            if (!string.IsNullOrEmpty(keywords))
            {
                books = books.Where(b => b.Title.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.BookAuthor.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.Isbn1.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.Publisher.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.Isbn2.ToUpper().Contains(keywords.ToUpper()));
            }

            if (!string.IsNullOrEmpty(bookPublisher))
                books = books.Where(b => b.Publisher == bookPublisher);

            if (category != 0) books = books.Where(b => b.BookCategory == category);

            if (ageGroup != 0) books = books.Where(b => b.AgeGroup == ageGroup);

            if (!string.IsNullOrEmpty(yearFrom) && int.TryParse(yearFrom, out int n))
                books = books.Where(b => int.Parse(b.YearPublished) >= n);

            if (!string.IsNullOrEmpty(yearTo) && int.TryParse(yearTo, out int m))
                books = books.Where(b => int.Parse(b.YearPublished) <= m);

            switch (sortField)
            {
                case "latest":
                    books = books.OrderByDescending(b => b.DateAdded);
                    break;
                case "rating":
                    books = books.OrderByDescending(b => b.AverageRating);
                    break;
                case "views":
                    books = books.OrderByDescending(b => b.Answers.Count);
                    break;
                case "class":
                    books = books.OrderBy(b => b.Grade);
                    break;
                case "year":
                    books = books.OrderBy(b => b.YearPublished);
                    break;
                case "title":
                    books = books.OrderBy(b => b.Title);
                    break;
                case "author":
                    books = books.OrderBy(b => b.BookAuthor);
                    break;
                default:
                    books = books.OrderByDescending(b => b.DateAdded);
                    break;
            }

            Count = books.Count();

            if (CurrentPage > TotalPages)
                CurrentPage = TotalPages;

            var indexVm = new IndexBookViewModel()
            {
                Books = await books.Skip((CurrentPage - 1) * PageSize)
                    .Take(PageSize)
                    .ToListAsync(),

                Publishers = new SelectList(await publishers.Distinct().ToListAsync()),

                CurrentPage = CurrentPage,
                Count = Count,
                PageSize = PageSize,
                TotalPages = TotalPages,
                EnablePrevious = EnablePrevious,
                EnableNext = EnableNext
            };

            if (User.Identity.IsAuthenticated)
            {
                var booksIds = _context.MarkedBooks
                    .Where(mb => mb.UserId == user.Id)
                    .Select(mb => mb.BookId).ToList();

                indexVm.BooksIds = booksIds;
            }
            return View(indexVm);
        }





        public async Task<IActionResult> DetailsAdmin(int? id)
        {
            var book = await _context.Books
                .Include(b => b.Questions)
                .Include(b => b.Answers)
                .Include(b => b.BookRatings)
                .FirstOrDefaultAsync(m => m.Id == id);
            return View(book);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);

                var answer = await _context.Answers
                    .Include(a => a.Book)
                    .FirstOrDefaultAsync(a => a.BookId == id && a.UserId == user.Id);

                Book book;

                if (answer == null)
                {
                    book = _context.Books
                        .Include(b => b.Answers)
                        .Include(b => b.Questions)
                        .Include(b => b.BookRatings)
                        .Single(b => b.Id == id);

                }
                else { book = answer.Book; }

                var bookCommentsFromOthers =
                    _context.BookComments
                        .Include(bc => bc.User)
                        .ThenInclude(u => u.BookRatings)
                        .Where(bc => bc.UserId != user.Id && bc.Approved)
                        .Select(bc => new BookCommentViewModel
                        {
                            BookComment = bc,
                            User = bc.User,
                            BookRating = bc.User.BookRatings.SingleOrDefault(br => br.BookId == bc.BookId)
                        }).ToList();


                var bookOpinionsFromOthers =
                    _context.BookOpinions
                        .Include(bo => bo.User)
                        .ThenInclude(u => u.BookRatings)
                        .Where(bo => bo.UserId != user.Id && bo.Approved)
                        .Select(bo => new BookOpinionViewModel
                        {
                            BookOpinion = bo,
                            User = bo.User,
                            BookRating = bo.User.BookRatings.SingleOrDefault(br => br.BookId == bo.BookId)
                        }).ToList();


                var bookNoteText =
                     _context.BookNotes.SingleOrDefault(bn => bn.UserId == user.Id && bn.BookId == book.Id)?.Text;

                var bookComment = await _context.BookComments.SingleOrDefaultAsync(bc =>
                    bc.UserId == user.Id && bc.BookId == book.Id);

                var bookOpinion =
                   await  _context.BookOpinions.SingleOrDefaultAsync(bc =>
                        bc.UserId == user.Id && bc.BookId == book.Id);

                var rating = _context.BookRatings.SingleOrDefault(br => br.UserId == user.Id && br.BookId == id)?.Rating;

                var recommended = _context.Books.Take(4).ToList(); // change it later

                var opinionQuestionText = _context.Questions
                    .SingleOrDefault(q => q.QuestionType == QuestionTypes.Opinion && q.BookId == book.Id)?.Text;

                var booksIds = _context.MarkedBooks
                    .Where(mb => mb.UserId == user.Id)
                    .Select(mb => mb.BookId).ToList();

                var vm1 = new DetailsViewModel
                {
                    Answer = answer,
                    Book = book,
                    BookId = book.Id,
                    Recommended = recommended,
                    MyRating = rating,
                    UserType = user.UserType,
                    OpinionQuestion = opinionQuestionText,
                    BooksIds = booksIds,
                    BookComment = bookComment,
                    BookOpinion = bookOpinion,

                    BookNoteText = bookNoteText,
                    BookOpinionText = bookOpinion?.AnswerText,
                    BookCommentText = bookComment?.Text,

                    BookCommentsFromOthers = bookCommentsFromOthers,
                    BookOpinionsFromOthers = bookOpinionsFromOthers,
                };

                if (user.UserType == UserTypes.Parent)
                {
                    var studentIds = _context.StudentFamilies
                        .Where(uf => uf.FamilyId == user.Id)
                        .Select(uf => uf.StudentId)?.ToList();
                    var answers = _context.Answers.Where(
                        a => a.BookId == book.Id && studentIds.Contains(a.UserId))?.ToList();

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Knigosha.Core.Models;
using Knigosha.Core.Models.Enums;
using Knigosha.Core.ViewModels;
using Knigosha.Core.ViewModels.BookViewModels;
using Knigosha.Core.ViewModels.UserViewModels;
using Knigosha.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;

namespace Knigosha.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users
                .Include(au => au.UserRoles)
                .ThenInclude(ur => ur.Role)
                .Select(au => new IndexUserViewModel
            {
                Id = au.Id,
                UserType = au.UserType,
                Email = au.Email,
                DateAdded = au.DateAdded,
                DateEdited = au.DateEdited,
                LastLogin = au.LastLogin,
                UserName = au.UserName,
                LoginTimes = au.LoginTimes
            }).ToListAsync();

            return View(users);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null) return NotFound();
            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == id);


            return View(user);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null) return NotFound();
            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null) return NotFound();

            var editUserVm = new EditUserViewModel
            {
                Id = user.Id,
            };

            return View(editUserVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel editUserVm) { 
            if (ModelState.IsValid)
            {
                var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == editUserVm.Id);

                var newCreatedBook = new CreatedBook()
                {
                    Points = editUserVm.PointsForCreatedBook
                };

                user.DateEdited = DateTime.Now.ToString("d");
                user.CreatedBooks.Add(newCreatedBook);
                _context.CreatedBooks.Add(newCreatedBook);

                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(editUserVm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(editUserVm);
        }

        private bool UserExists(string id)
        {
            return _userManager.Users.Any(u => u.Id == id);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null) return NotFound();
            var user = await _userManager.Users
                .FirstOrDefaultAsync(u => u.Id == id);

            if (user == null) return NotFound();
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == id);

            switch (user.UserType)
            {
                case UserTypes.Student:
                    var countSc = await _context.StudentClasses.CountAsync(sc => sc.StudentId == user.Id);
                    var countSf = await _context.StudentFamilies.CountAsync(sc => sc.StudentId == user.Id);
                    var messages = await _context.Messages.CountAsync(m => m.SenderId == user.Id || m.RecipientId == user.Id);

                    if (messages == 1) _context.Messages.Remove(_context.Messages.Single(m => m.SenderId == user.Id || m.RecipientId == user.Id));
                    else if (messages > 1) _context.Messages.RemoveRange(_context.Messages.Where(m => m.SenderId == user.Id || m.RecipientId == user.Id).ToList());

                    if (countSc == 1) _context.StudentClasses.Remove(_context.StudentClasses.Single(sc => sc.StudentId == user.Id));
                    else if (countSc > 1) _context.StudentClasses.RemoveRange(_context.StudentClasses.Where(sc => sc.StudentId == user.Id).ToList());

                    if (countSf == 1) _context.StudentFamilies.Remove(_context.StudentFamilies.Single(sc => sc.StudentId == user.Id));
                    else if (countSf > 1) _context.StudentFamilies.RemoveRange(_context.StudentFamilies.Where(sc => sc.StudentId == user.Id).ToList());
                    break;

                case UserTypes.Parent:
                    var countSf2 = await _context.StudentFamilies.CountAsync(sc => sc.FamilyId == user.Id);
                    var messages2 = await _context.Messages.CountAsync(m => m.SenderId == user.Id || m.RecipientId == user.Id);

                    if (messages2 == 1) _context.Messages.Remove(_context.Messages.Single(m => m.SenderId == user.Id));
                    else if (messages2 > 1) _context.Messages.RemoveRange(_context.Messages.Where(m => m.SenderId == user.Id || m.RecipientId == user.Id).ToList());

                    if (countSf2 == 1) _context.StudentFamilies.Remove(_context.StudentFamilies.Single(sf => sf.FamilyId == user.Id));
                    else if (countSf2 > 1) _context.StudentFamilies.RemoveRange(_context.StudentFamilies.Where(sf => sf.FamilyId == user.Id).ToList());
                    break;

                case UserTypes.Teacher:
                    var countSf3 = await _context.StudentClasses.CountAsync(sc => sc.ClassId == user.Id);
                    var messages3 = await _context.Messages.CountAsync(m => m.SenderId == user.Id || m.RecipientId == user.Id);

                    if (messages3 == 1) _context.Messages.Remove(_context.Messages.Single(m => m.SenderId == user.Id));
                    else if (messages3 > 1) _context.Messages.RemoveRange(_context.Messages.Where(m => m.SenderId == user.Id || m.RecipientId == user.Id).ToList());

                    if (countSf3 == 1) _context.StudentClasses.Remove(_context.StudentClasses.Single(sc => sc.ClassId == user.Id));
                    else if (countSf3 > 1) _context.StudentClasses.RemoveRange(_context.StudentClasses.Where(sc => sc.ClassId == user.Id).ToList());
                    break;
            }
            await _userManager.DeleteAsync(user);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_DashboardPartial.cshtml
<ul class="nav nav-tabs" id="dashboard">
    <li class="nav-item">
        <a class="nav-link" asp-controller="Book" asp-action="IndexAdmin">Книги</a>
    </li>
    <li class="nav-item">
        <a class="nav-link"asp-controller="Users" asp-action="Index">Пользователи</a>
    </li>
    <li class="nav-item">
        <a class="nav-link"asp-controller="UserSubscription" asp-action="Index">Подписки</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Subscriptions" asp-action="IndexAdmin">Абонементы</a>
    </li>
    <li class="nav-item">
        <a class="nav-link"  asp-controller="Texts" asp-action="IndexAdmin">Новости/авторы</a>
    </li> 
    <li class="nav-item">
        <a class="nav-link"  asp-controller="Answer" asp-action="Index">Рестарт</a>
    </li>  
    <li class="nav-item">
        <a class="nav-link"  asp-controller="Answer" asp-action="CommentsAndOpinions">Ответы</a>
    </li> 
    <li class="nav-item">
        <a class="nav-link"  asp-controller="Answer" asp-action="Reports">Рапорты</a>
    </li>
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="https://fonts.googleapis.com/css?family=Kurale&display=swap&subset=cyrillic" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    <link href="~/lib/select2-4.0.8/dist/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/select2-bootstrap4-theme-master/dist/select2-bootstrap4.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li><a asp-controller="Home" asp-action="Index">
                            <img src="~/skin/logo_header.png" style="width: 130px; "/></a></li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Book" asp-action="Index" style="font-size: 20px; padding-left: 40px">Книги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Help" style="font-size: 20px; padding-left: 20px">Помощь</a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="IndexAdmin" style="font-size: 20px; padding-left: 20px">Администрация</a>
                                }
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <partial name="_CookieConsentPartial" />
        <main id="content" style="padding-top:0; padding-bottom: 0;">
            @RenderBody()
        </main>
    </div>
    <footer>
        <div id="footer">
            <div class="container">
                <a asp-controller="Home" asp-action="Index"></a>
                <div class="row">
                    <div class="col-md-3">
                        <h5>Книговище</h5>
                        <a asp-controller="Home" asp-action="Team">О нас</a><div style="height:15px;"></div>
                        <a asp-controller="Subscriptions" asp-action="Index">Типы абонементов</a><div style="height:15px;"></div>
                        <a asp-controller="Texts" asp-action="Index">Блог</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="Partners">Партнеры</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="TermsOfUse">Условия пользования</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="Policy">Политика конфиденциальности</a><div style="height:15px;"></div>
                    </div>
                    <div class="col-md-3">
                        <h5>Помощь</h5>
                        <a asp-controller="Home" asp-action="Help">Как это работает?</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="CreateClass">Как создать группу КЛАСС</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="UseClass">Как использовать группу КЛАСС</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="CreateFamily">Как создать группу СЕМЬЯ</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="UseFamily">Как использовать группу СЕМЬЯ</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="Activate">Активировать подписку с помощью ключа</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="Faq">Часто задаваемые вопросы</a><div style="height:15px;"></div>
                    </div>
                    <div class="col-md-3">
                        <h5>Викторины</h5>
                        <a asp-controller="Book" asp-action="Index" asp-route-category="1">Художественная литература</a><div style="height:15px;"></div>
                        <a asp-controller="Book" asp-action="Index" asp-route-category="2">Научнопопулярная литература</a><div style="height:15px;"></div>
                        <a asp-controller="Home" asp-action="CreateQuiz">Создать викторину</a><div style="height:15px;"></div>
                    </div>
                    <div class="col-md-3">
                        <h5>Связаться с нами</h5>
                        <div class="contact"><span class="icon"><i class="fa fa-envelope"></i></span> <a href="mailto:info@knigovishe.ru">info@knigovishe.ru</a></div><div style="height:5px;"></div>
                        <div class="contact" style="white-space:nowrap;"><span class="icon"><i class="fa fa-facebook-f"></i></span> <a href="https://www.facebook.com/Knigovishte/" target="_blank">www.facebook.com/Knigovishte</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div style="height: 50px; background: #232323; color: white">
            <div style="line-height: 50px;" class="container" >&copy; 2019 - Knigovishe.ru</div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js" ></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>