Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Timers;
using Knigosha.Core.Models;
using Knigosha.Core.Models.Enums;
using Knigosha.Core.ViewModels.AnswerViewModel;
using Knigosha.Core.ViewModels.ManageViewModels;
using Knigosha.Persistence;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Knigosha.Controllers
{
    public class AnswerController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private int _bookId;


        public AnswerController(
            UserManager<ApplicationUser> userManager,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<ActionResult> Index()
        {
            var answersWithReasonToRestart = await _context.Answers
                .Include(a => a.User)
                .Include(a => a.Book)
                .Where(a => !string.IsNullOrEmpty(a.ReasonForRestart) &&
                            a.User.Student.StudentClasses.Count == 0 &&
                            a.User.Student.StudentFamilies.Count == 0).ToListAsync();

            return View(answersWithReasonToRestart);
        }

        public async Task<ActionResult> CommentsAndOpinions(string act, int id, string type)
        {
            if (act == "approve")
            {
                if (type == "comment")
                {
                    var bookComment = await _context.BookComments.SingleAsync(bc => bc.Id == id);
                    bookComment.Approved = true;
                    _context.BookComments.Update(bookComment);
                    await _context.SaveChangesAsync();
                }
                else if (type == "opinion")
                {
                    var bookOpinion = await _context.BookOpinions.SingleAsync(bc => bc.Id == id);
                    bookOpinion.Approved = true;
                    _context.BookOpinions.Update(bookOpinion);
                    await _context.SaveChangesAsync();
                }
            }

            var list = await _context.BookComments
                .Include(bc => bc.User)
                .Include(bc => bc.Book)
                .Where(bc => bc.Share).ToListAsync();

            var list2 = await _context.BookOpinions
                .Include(bc => bc.User)
                .Include(bc => bc.Book)
                .Where(bc => bc.Share).ToListAsync();

            var vm = new CommentsAndOpinionsViewModel
            {
                BookComments = list,
                BookOpinions = list2
            };

          return View(vm);
        }

        public async Task<IActionResult> DeleteBookComment(int id)
        {
            var bookComment = await _context.BookComments.SingleAsync(bc => bc.Id == id);
            _context.BookComments.Remove(bookComment);
            await _context.SaveChangesAsync();

            return RedirectToAction("CommentsAndOpinions");
        }

        public async Task<IActionResult> DeleteBookOpinion(int id)
        {
            var bookOpinion = await _context.BookOpinions.SingleAsync(bc => bc.Id == id);
            _context.BookOpinions.Remove(bookOpinion);
            await _context.SaveChangesAsync();

            return RedirectToAction("CommentsAndOpinions");
        }




        public async Task<ActionResult> Reports()
        {
            var reports = await _context.Reports
                .Include(r => r.Book)
                .ToListAsync();

            return View(reports);
        }

        public async Task<ActionResult> Quiz(string act, int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var book = await _context.Books
                .Include(b => b.Questions)
                .SingleAsync(b => b.Id == id);
            var rating = _context.BookRatings.SingleOrDefault(br => br.UserId == user.Id && br.BookId == id)?.Rating;
            _bookId = book.Id;

            var quizVm = new QuizViewModel
            {
                Book = book,
                HasAccess = HasAccess(user),
                MyRating = rating,
            };

            if (act == "start")
            {
                var questions = _context.Questions.Where(q =>
                    q.BookId == book.Id && q.QuestionType == QuestionTypes.ContentComprehension).ToList();

                quizVm.Questions = questions;

                if (_context.Answers.Count(a => a.BookId == book.Id && a.UserId == user.Id) == 0)
                {
                    var newAnswer = new Answer(user, book)
                    {
                        UserId = user.Id,
                        BookId = book.Id,
                        QuizType = user.UserType == UserTypes.Student ? QuizTypes.Individual : QuizTypes.Group,
                        Started = DateTime.Now
                    };
                    _context.Answers.Add(newAnswer);
                    await _context.SaveChangesAsync();
                    quizVm.Points = 0;
                    quizVm.CurrentQuestion = 0;
                    quizVm.CurrentSecond = 1800;
                }
                else
                {
                    var answer = await _context.Answers.SingleAsync(a => a.BookId == book.Id && a.UserId == user.Id);
                    var now = DateTime.Now;
                    var timeSPan = now - answer.Started;
                    var seconds = (int)timeSPan.TotalSeconds;
                    quizVm.Points = answer.Points;
                    quizVm.CurrentQuestion = answer.CurrentQuestion;
                    quizVm.CurrentSecond = 1800 - seconds;
                }

                return View("QuizAction", quizVm);
            }
            return View(quizVm);
        }

        public bool HasAccess(ApplicationUser user)
        {
            if (user.Email == "a@a.com") return true;

            var activeSubscriptions = _context.UserSubscriptions.Include(us => us.Subscription)
                .Where(us => us.UserId == user.Id && us.ActivatedOn != null).ToList();

            var freeSubscription = activeSubscriptions
                .Find(us => us.Subscription.SubscriptionType == SubscriptionTypes.FreeClass ||
                            us.Subscription.SubscriptionType == SubscriptionTypes.FreeFamily ||
                            us.Subscription.SubscriptionType == SubscriptionTypes.FreeStudent);

            var duration = DateTime.Today.Subtract((DateTime)freeSubscription.ActivatedOn);
            TimeSpan maxDuration = TimeSpan.FromDays(14);

            var count = _context.Answers.Count(a => a.UserId == user.Id);

            var hasValidFreeSubscription = TimeSpan.Compare(duration, maxDuration) < 0 && count < 3;

            var paidSubscription = activeSubscriptions
                .Find(us => us.Subscription.SubscriptionType == SubscriptionTypes.Class ||
                            us.Subscription.SubscriptionType == SubscriptionTypes.Family ||
                            us.Subscription.SubscriptionType == SubscriptionTypes.Student);

            var hasValidPaidSubscription = paidSubscription != null && DateTime.Compare((DateTime)paidSubscription.ActivatedOn,
                                               DateTime.Parse(paidSubscription.Subscription.ValidUntil)) < 0;

            return (hasValidFreeSubscription || hasValidPaidSubscription);
        }
    }
}

Controllers/BookController.cs
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Knigosha.Core.Models;
using Knigosha.Core.Models.Enums;
using Knigosha.Core.ViewModels;
using Knigosha.Core.ViewModels.BookViewModels;
using Knigosha.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Knigosha.Controllers
{
    public class BookController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BookController(ApplicationDbContext context,
            IHostingEnvironment environment,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _hostingEnvironment = environment;
            _context = context;
        }

        public int CurrentPage { get; set; } = 1;

        public int Count { get; set; }

        public int PageSize { get; set; } = 24;

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));

        public bool EnablePrevious => CurrentPage > 1;

        public bool EnableNext => CurrentPage < TotalPages;


        public async Task<IActionResult> IndexAdmin()
        {
            return View(await _context.Books.ToListAsync());
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(string keywords, string bookPublisher, BookCategories category, AgeGroups ageGroup, string yearFrom, string yearTo, string sortField, int page = 1)
        {
            var user = await _userManager.GetUserAsync(User);

            var books = _context.Books
                .Include(b => b.Answers)
                .Include(b => b.BookRatings)
                .AsQueryable();

            CurrentPage = page == 0 ? 1 : page;

            var publishers = books.Select(b => b.Publisher);

            if (!string.IsNullOrEmpty(keywords))
            {
                books = books.Where(b => b.Title.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.BookAuthor.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.Isbn1.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.Publisher.ToUpper().Contains(keywords.ToUpper()) ||
                                         b.Isbn2.ToUpper().Contains(keywords.ToUpper()));
            }

            if (!string.IsNullOrEmpty(bookPublisher))
                books = books.Where(b => b.Publisher == bookPublisher);

            if (category != 0) books = books.Where(b => b.BookCategory == category);

            if (ageGroup != 0) books = books.Where(b => b.AgeGroup == ageGroup);

            if (!string.IsNullOrEmpty(yearFrom) && int.TryParse(yearFrom, out int n))
                books = books.Where(b => int.Parse(b.YearPublished) >= n);

            if (!string.IsNullOrEmpty(yearTo) && int.TryParse(yearTo, out int m))
                books = books.Where(b => int.Parse(b.YearPublished) <= m);

            switch (sortField)
            {
                case "latest":
                    books = books.OrderByDescending(b => b.DateAdded);
                    break;
                case "rating":
                    books = books.OrderByDescending(b => b.AverageRating);
                    break;
                case "views":
                    books = books.OrderByDescending(b => b.Answers.Count);
                    break;
                case "class":
                    books = books.OrderBy(b => b.Grade);
                    break;
                case "year":
                    books = books.OrderBy(b => b.YearPublished);
                    break;
                case "title":
                    books = books.OrderBy(b => b.Title);
                    break;
                case "author":
                    books = books.OrderBy(b => b.BookAuthor);
                    break;
                default:
                    books = books.OrderByDescending(b => b.DateAdded);
                    break;
            }

            Count = books.Count();

            if (CurrentPage > TotalPages)
                CurrentPage = TotalPages;

            var indexVm = new IndexBookViewModel()
            {
                Books = await books.Skip((CurrentPage - 1) * PageSize)
                    .Take(PageSize)
                    .ToListAsync(),

                Publishers = new SelectList(await publishers.Distinct().ToListAsync()),

                CurrentPage = CurrentPage,
                Count = Count,
                PageSize = PageSize,
                TotalPages = TotalPages,
                EnablePrevious = EnablePrevious,
                EnableNext = EnableNext
            };

            if (User.Identity.IsAuthenticated)
            {
                var booksIds = _context.MarkedBooks
                    .Where(mb => mb.UserId == user.Id)
                    .Select(mb => mb.BookId).ToList();

                indexVm.BooksIds = booksIds;
            }
            return View(indexVm);
        }





        public async Task<IActionResult> DetailsAdmin(int? id)
        {
            var book = await _context.Books
                .Include(b => b.Questions)
                .Include(b => b.Answers)
                .Include(b => b.BookRatings)
                .FirstOrDefaultAsync(m => m.Id == id);
            return View(book);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);

                var answer = await _context.Answers
                    .Include(a => a.Book)
                    .FirstOrDefaultAsync(a => a.BookId == id && a.UserId == user.Id);

                Book book;

                if (answer == null)
                {
                    book = _context.Books
                        .Include(b => b.Answers)
                        .Include(b => b.Questions)
                        .Include(b => b.BookRatings)
                        .Single(b => b.Id == id);

                }
                else { book = answer.Book; }

                var bookCommentsFromOthers =
                    _context.BookComments
                        .Include(bc => bc.User)
                        .ThenInclude(u => u.BookRatings)
                        .Where(bc => bc.UserId != user.Id && bc.Approved)
                        .Select(bc => new BookCommentViewModel
                        {
                            BookComment = bc,
                            User = bc.User,
                            BookRating = bc.User.BookRatings.SingleOrDefault(br => br.BookId == bc.BookId)
                        }).ToList();


                var bookOpinionsFromOthers =
                    _context.BookOpinions
                        .Include(bo => bo.User)
                        .ThenInclude(u => u.BookRatings)
                        .Where(bo => bo.UserId != user.Id && bo.Approved)
                        .Select(bo => new BookOpinionViewModel
                        {
                            BookOpinion = bo,
                            User = bo.User,
                            BookRating = bo.User.BookRatings.SingleOrDefault(br => br.BookId == bo.BookId)
                        }).ToList();


                var bookNoteText =
                     _context.BookNotes.SingleOrDefault(bn => bn.UserId == user.Id && bn.BookId == book.Id)?.Text;

                var bookComment = await _context.BookComments.SingleOrDefaultAsync(bc =>
                    bc.UserId == user.Id && bc.BookId == book.Id);

                var bookOpinion =
                   await  _context.BookOpinions.SingleOrDefaultAsync(bc =>
                        bc.UserId == user.Id && bc.BookId == book.Id);

                var rating = _context.BookRatings.SingleOrDefault(br => br.UserId == user.Id && br.BookId == id)?.Rating;

                var recommended = _context.Books.Take(4).ToList(); // change it later

                var opinionQuestionText = _context.Questions
                    .SingleOrDefault(q => q.QuestionType == QuestionTypes.Opinion && q.BookId == book.Id)?.Text;

                var booksIds = _context.MarkedBooks
                    .Where(mb => mb.UserId == user.Id)
                    .Select(mb => mb.BookId).ToList();

                var vm1 = new DetailsViewModel
                {
                    Answer = answer,
                    Book = book,
                    BookId = book.Id,
                    Recommended = recommended,
                    MyRating = rating,
                    UserType = user.UserType,
                    OpinionQuestion = opinionQuestionText,
                    BooksIds = booksIds,
                    BookComment = bookComment,
                    BookOpinion = bookOpinion,

                    BookNoteText = bookNoteText,
                    BookOpinionText = bookOpinion?.AnswerText,
                    BookCommentText = bookComment?.Text,

                    BookCommentsFromOthers = bookCommentsFromOthers,
                    BookOpinionsFromOthers = bookOpinionsFromOthers,
                };

                if (user.UserType == UserTypes.Parent)
                {
                    var studentIds = _context.StudentFamilies
                        .Where(uf => uf.FamilyId == user.Id)
                        .Select(uf => uf.StudentId)?.ToList();
                    var answers = _context.Answers.Where(
                        a => a.BookId == book.Id && studentIds.Contains(a.UserId))?.ToList();

Views/Answer/CommentsAndOpinions.cshtml
@model Knigosha.Core.ViewModels.AnswerViewModel.CommentsAndOpinionsViewModel
@{
    ViewData["Title"] = "Мнения и комментарии";
}
    <div class="container" style="min-height: calc(100vh - 360px); margin-bottom: 30px; margin-top: 15px;">
        <partial name="_DashboardPartial" />

        <table class="table table-bordered adminTable" style="margin-top: 30px;">
            <tr>
                <th style="width: 15%">Юзер</th>
                <th style="width: 20%">Книга</th>
                <th >Комментарий</th>
                <th style="width: 12%"></th>
                <th style="width: 5%"></th>
            </tr>

            @for (int i = 0; i < Model.BookComments.Count; i++)
            {
                <tr>
                    <td align="center">@Model.BookComments[i].User.FullName [@Model.BookComments[i].User.UserName]</td>
                    <td align="center">#@Model.BookComments[i].Book.Id - @Model.BookComments[i].Book.Title - @Html.DisplayTextFor(m => m.BookComments[i].Book.AgeGroup)</td>
                    <td align="center">@Model.BookComments[i].Text</td>
                    <td align="center">@if(Model.BookComments[i].Approved){<text>Показан</text>}else{<a asp-controller="Answer" asp-action="CommentsAndOpinions" asp-route-type="comment" asp-route-act="approve" asp-route-id="@Model.BookComments[i].Id">Подтвердить</a>}</td>
                    <td align="center"><a asp-controller="Answer" asp-action="DeleteBookComment" asp-route-id="@Model.BookComments[i].Id"><i id="deleteIcon" class="fa fa-trash-o"></i></a></td>
                </tr>
            }

        </table>
        <div style="height: 40px"></div>
        <table class="table table-bordered adminTable" style="margin-top: 30px;">
            <tr>
                <th style="width: 15%">Юзер</th>
                <th style="width: 20%">Книга</th>
                <th>Ответ</th>
                <th style="width: 12%"></th>
                <th style="width: 5%"></th>

            </tr>

            @for (int i = 0; i < Model.BookOpinions.Count; i++)
            {
                <tr>
                    <td align="center">@Model.BookOpinions[i].User.FullName [@Model.BookOpinions[i].User.UserName]</td>
                    <td align="center">#@Model.BookOpinions[i].Book.Id - @Model.BookOpinions[i].Book.Title - @Html.DisplayTextFor(m => m.BookOpinions[i].Book.AgeGroup)</td>
                    <td align="center">@Model.BookOpinions[i].AnswerText</td>
                    <td align="center">@if(Model.BookOpinions[i].Approved){<text>Показан</text>}else{<a asp-controller="Answer" asp-action="CommentsAndOpinions" asp-route-type="opinion" asp-route-act="approve" asp-route-id="@Model.BookOpinions[i].Id">Подтвердить</a>}</td>
                    <td align="center"><a asp-controller="Answer" asp-action="DeleteBookOpinion" asp-route-id="@Model.BookOpinions[i].Id"><i id="deleteIcon" class="fa fa-trash-o"></i></a></td>
                </tr>
            }

        </table>
    </div>

Views/Answer/Index.cshtml
@model List<Knigosha.Core.Models.Answer>
@{
    ViewData["Title"] = "Запросы на рестарт ";
}
<div class="container" style="min-height: calc(100vh - 360px); margin-bottom: 30px; margin-top: 15px;">
<partial name="_DashboardPartial"/>

<table class="table table-bordered adminTable"  style="margin-top: 30px;">
    <tr>
        <th>Решена</th>
        <th>Викторина</th>
        <th>Причина</th>
        <th>Ученик</th>
        <th style="width: 7%">Очков</th>
        <th style="width: 10%"></th>
        <th style="width: 10%"></th>
        <th style="width: 10%"></th>
    </tr>
    @for (int i = 0; i < Model.Count; i++)
    {
        <tr>
            <td align="center">@Model[i].DateTime</td>
            <td align="center">#@Model[i].BookId - @Model[i].Book.Title - @Html.DisplayTextFor(m => m[i].Book.AgeGroup)</td>
            <td align="center">@Model[i].ReasonForRestart</td>
            <td align="center">@Model[i].User.FullName [@Model[i].User.UserName]</td>
            <td align="center">@Math.Ceiling(Model[i].Points)</td>
            <td align="center"><a asp-controller="Manage" asp-action="Answers" asp-route-type="reset" asp-route-act="reset" asp-route-id="@Model[i].Id">Рестарт</a></td>
            <td align="center"><a asp-controller="Manage" asp-action="Answers" asp-route-type="reset" asp-route-act="refuse" asp-route-id="@Model[i].Id">Отказать</a></td>
            <td align="center"><a asp-controller="Manage" asp-action="Messages" asp-route-type="send" asp-route-to="@Model[i].User.Id" asp-route-subject="#@Model[i].BookId - @Model[i].Book.Title - @Html.DisplayTextFor(m => m[i].Book.AgeGroup)">Ответить</a></td>
        </tr>
    }

</table>
</div>

Views/Answer/QuizAction.cshtml
@using System.Globalization
@using Knigosha.Core.Models
@using Microsoft.AspNetCore.Http
@model Knigosha.Core.ViewModels.ManageViewModels.QuizViewModel
@{
    ViewData["Title"] = "Викторина";
}

<script>
    var k = @Model.Book.PointsForRightAnswer;

    var questions = [
        @foreach (var question in Model.Questions)
        {
            <text>{
            "title": "@question.Text",
            "answer1": "@question.RightAnswer",
            "answer2": "@question.WrongAnswer1",
            "answer3": "@question.WrongAnswer2",
            "type": @((int)question.QuestionType)},</text>
        }];

    var texts_correct = ["Это правильный ответ!", "Молодец!", "Верно!", "Супер!", "Так держать!", "Правильно!", "В точку!", "Отлично!", "Умница!", "Молодчина!"];
    var texts_wrong = ["Это неправильный ответ!", "Неверно!", "Ошибка!", "Этот ответ неверен!", "Ты можешь лучше!"];

    console.log(k, questions);

    var bid = @Model.Book.Id;
    var stopTimer = false;
    var finish = '/Book/Details?id=@Model.Book.Id';

 
    var q = @Model.CurrentQuestion;
    var points = @Model.Points;

    var s = @Model.CurrentSecond;
</script>

<div class="shadow_bg">
    <div class="inner" style="padding-top:30px;padding-bottom:30px;">
        <div class="quiz_popup" style="padding-top:0px;">
            <div class="questionWrap">
                <div id="question">
                </div>
                <div style="height:50px;"></div>
                <a href="javascript:;" style="color: gray;" onclick="$(this).hide();$('#report').show();">
                    <i class="fa fa-bell"></i> Сообщить о проблеме
                </a>
                <div id="report" data-id="@Model.Book.Id" style="display:none;">
                    Есть неточность в вопросе или ответах? Опиши проблему:
                    <div style="height:10px;"></div>
                    <textarea style="width:100%;height:300px;"></textarea>
                    <div style="height:10px;"></div>
                    <a href="javascript:;" onclick="sendReport()" class="button">Отправить</a>
                </div>
            </div>
            <div class="visible-mobile" style="height:20px;"></div>
            <div id="dots">
                @if (Model.Book.NumberOfQuestionsForResponses == 5)
                {
                    <div class="dot dot1"></div>
                    <div class="dot dot2"></div>
                    <div class="dot dot3"></div>
                    <div class="dot dot4"></div>
                    <div class="visible-mobile" style="height:5px;"></div>
                    <div class="dot dot5"></div>}
                else if (Model.Book.NumberOfQuestionsForResponses == 10)
                {
                    <div class="dot dot1"></div>
                    <div class="dot dot2"></div>
                    <div class="dot dot3"></div>
                    <div class="dot dot4"></div>
                    <div class="visible-mobile" style="height:5px;"></div>
                    <div class="dot dot5"></div>
                    <div class="dot dot6"></div>
                    <div class="dot dot7"></div>
                    <div class="dot dot8"></div>
                    <div class="visible-mobile" style="height:5px;"></div>
                    <div class="dot dot9"></div>
                    <div class="dot dot10"></div>
                }
                else
                {
                    <div class="dot dot1"></div>
                    <div class="dot dot2"></div>
                    <div class="dot dot3"></div>
                    <div class="dot dot4"></div>
                    <div class="visible-mobile" style="height:5px;"></div>
                    <div class="dot dot5"></div>
                    <div class="dot dot6"></div>
                    <div class="dot dot7"></div>
                    <div class="dot dot8"></div>
                    <div class="visible-mobile" style="height:5px;"></div>
                    <div class="dot dot9"></div>
                    <div class="dot dot10"></div>
                    <div class="dot dot11"></div>
                    <div class="dot dot12"></div>
                    <div class="visible-mobile" style="height:5px;"></div>
                    <div class="dot dot13"></div>
                    <div class="dot dot14"></div>
                    <div class="dot dot15"></div>}
                <div id="points">
                    очков: <span style="font-weight: bold" id="counter"></span>
                </div>
            </div>
        </div>
        <div style="height:30px;"></div>
        <div class="quiz_info">
            <div id="timerLine" class="visible-desktop">
                <div id="timerFill"></div>
                <div id="timerInfo">* осталось времени для решения</div>
            </div>
            <div id="timerCircle"></div>
            <div id="timerText">
                <span id="timer"></span><br>
                <span>минуты</span>
            </div>
            <div class="visible-mobile" style="height:50px;"></div>
            <div class="visible-desktop">
                <div id="bookInfo">
                    <table class="sc">
                        <tr>
                            <td class="book_info_left" valign="top">
                                <div class="visible-desktop">
                                    <a asp-controller="Book" asp-action="Details" asp-route-id="@Model.Book.Id">
                                        <img src="/uploads/@Model.Book.CoverPhoto" style="border-radius: 15px; max-width: 100px;">
                                    </a>
                                </div>
                            </td>
                            <td valign="top" class="book_info_right">
                                <span style="font-size:20px; font-weight: bold">@Model.Book.Title /</span> от @Model.Book.BookAuthor
                                <div style="height:10px;"></div>
                                <div class="yellow">
                                    <span style="font-weight: bold">викторина для @Html.DisplayFor(m => m.Book.AgeGroup) /</span>
                                    <i>автор викторины: <span style="font-weight: bold">@Model.Book.QuestionsAuthor</span></i>
                                </div>
                                <div style="height:10px;"></div>
                                <i>
                                    Категория: @Html.DisplayFor(m => m.Book.BookCategory)<br>
                                    Год на издания: @Model.Book.YearPublished<br>
                                    Издательство: @Model.Book.Publisher<br>
                                    @if (!string.IsNullOrEmpty(Model.Book.Translator))
                                    {
                                        <text>Переводчик: </text>@Model.Book.Translator
                                    }<br>
                                </i>
                                <div style="height:10px;"></div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div style="height:50px;"></div>
        </div>
    </div>
</div>

Views/Answer/Reports.cshtml
@model List<Knigosha.Core.Models.Report>
@{
    ViewData["Title"] = "Рапорты";
}
<div class="container" style="min-height: calc(100vh - 360px); margin-bottom: 30px; margin-top: 15px;">
    <partial name="_DashboardPartial"/>

    <table class="table table-bordered adminTable"  style="margin-top: 30px;">
        <tr>
            <th style="width: 15%">Дата</th>
            <th style="width: 20%">Книга</th>
            <th style="width: 8%">Вопрос</th>
            <th>Причина</th>
        </tr>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td align="center">@Model[i].DateTime</td>
                <td align="center">#@Model[i].Book.Id - @Model[i].Book.Title - @Html.DisplayTextFor(m => m[i].Book.AgeGroup)</td>
                <td align="center">#@Model[i].Question</td>
                <td align="center">@Model[i].Text</td>
            </tr>
        }

    </table>
</div>