Controllers/SubscriptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Knigosha.Core.Models;
using Knigosha.Core.Models.Enums;
using Knigosha.Persistence;

namespace Knigosha.Controllers
{
    public class SubscriptionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubscriptionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexAdmin()
        {
            return View(await _context.Subscriptions.ToListAsync());
        }

        public async Task<IActionResult> Index()
        {
            var notFreeSubscriptions = _context.Subscriptions
                .Where(s => s.SubscriptionType != SubscriptionTypes.FreeStudent &&
                            s.SubscriptionType != SubscriptionTypes.FreeFamily &&
                            s.SubscriptionType != SubscriptionTypes.FreeClass);

            return View(await notFreeSubscriptions.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var subscription = await _context.Subscriptions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subscription == null) return NotFound();
            return View(subscription);
        }

        public IActionResult Create()
        {
            var subscription = new Subscription();
            return View(subscription);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubscriptionType, Name, CurrentPrice,OldPrice,Discount,MaxQuizzes,NumberOfStudentProfiles,NumberOfParentProfiles,NumberOfTeacherProfiles,ValidUntil,BankData,Text1,Text2,Text3")] Subscription subscription)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subscription);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexAdmin));
            }
            return View(subscription);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound(); 

            var subscription = await _context.Subscriptions.FindAsync(id);
            if (subscription == null) return NotFound();
            return View(subscription);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name, SubscriptionType,CurrentPrice,OldPrice,Discount,MaxQuizzes,NumberOfStudentProfiles,NumberOfParentProfiles,NumberOfTeacherProfiles,ValidUntil,BankData,Text1,Text2,Text3")] Subscription subscription)
        {
            if (id != subscription.Id) return NotFound(); 

            if (ModelState.IsValid)
            {
                subscription.DateEdited = DateTime.Now.ToString("d");
                try
                {
                    _context.Update(subscription);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubscriptionExists(subscription.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(IndexAdmin));
            }
            return View(subscription);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var subscription = await _context.Subscriptions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subscription == null) return NotFound();
            return View(subscription);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subscription = await _context.Subscriptions.FindAsync(id);
            _context.Subscriptions.Remove(subscription);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexAdmin));
        }

        private bool SubscriptionExists(int id)
        {
            return _context.Subscriptions.Any(e => e.Id == id);
        }
    }
}

Views/Subscriptions/Create.cshtml
@using Knigosha.Core.Models.Enums
@model Knigosha.Core.Models.Subscription

@{
    ViewData["Title"] = "Новый абонемент";
}
<div class="container">
    <partial name="_DashboardPartial" />
    <div>
        <div class="header">
            <h4>Новый абонемент</h4>
            <a asp-action="IndexAdmin" class="btn btn btn-light ">Назад к абонементам</a>
        </div>
        <hr />
        <form asp-action="Create" class="inputAdmin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <select asp-for="Name" asp-items="Html.GetEnumSelectList<SubscriptionNames>()" class="form-control"><option value=""> - Выберите имя абонемента - </option></select>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubscriptionType"></label>
                <select asp-for="SubscriptionType" asp-items="Html.GetEnumSelectList<SubscriptionTypes>()" class="form-control"><option value=""> - Выберите тип абонемента - </option></select>
                <span asp-validation-for="SubscriptionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrentPrice"></label>
                <input asp-for="CurrentPrice" class="form-control" />
                <span asp-validation-for="CurrentPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OldPrice"></label>
                <input asp-for="OldPrice" class="form-control" />
                <span asp-validation-for="OldPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxQuizzes"></label>
                <input asp-for="MaxQuizzes" class="form-control" />
                <span asp-validation-for="MaxQuizzes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfStudentProfiles"></label>
                <input asp-for="NumberOfStudentProfiles" class="form-control" />
                <span asp-validation-for="NumberOfStudentProfiles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfParentProfiles"></label>
                <input asp-for="NumberOfParentProfiles" class="form-control" />
                <span asp-validation-for="NumberOfParentProfiles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfTeacherProfiles"></label>
                <input asp-for="NumberOfTeacherProfiles" class="form-control" />
                <span asp-validation-for="NumberOfTeacherProfiles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidUntil"></label>
                <input asp-for="ValidUntil" class="form-control" />
                <span asp-validation-for="ValidUntil" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankData"></label>
                <textarea rows="2" asp-for="BankData" class="form-control"></textarea>
                <span asp-validation-for="BankData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text1"></label>
                <textarea rows="2" asp-for="Text1" class="form-control"></textarea>
                <span asp-validation-for="Text1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text2"></label>
                <textarea rows=2 asp-for="Text2" class="form-control"></textarea>
                <span asp-validation-for="Text2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text3"></label>
                <textarea rows="2" asp-for="Text3" class="form-control"></textarea>
                <span asp-validation-for="Text3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить абонемент" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Subscriptions/Delete.cshtml
@model Knigosha.Core.Models.Subscription

@{
    ViewData["Title"] = "Удалить абонемент";
}
<div class="container">
    <partial name="_DashboardPartial" />
    <div>
        <div class="header">
            <h4>Вы уверены, что хотите удалить этот абонемент?</h4>
            <a asp-action="IndexAdmin" class="btn btn btn-light ">Назад к абонементам</a>
        </div>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.SubscriptionType)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.SubscriptionType)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.CurrentPrice)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.CurrentPrice)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.OldPrice)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.OldPrice)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Discount)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Discount)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.MaxQuizzes)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.MaxQuizzes)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.NumberOfStudentProfiles)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NumberOfStudentProfiles)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.NumberOfParentProfiles)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NumberOfParentProfiles)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.NumberOfTeacherProfiles)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NumberOfTeacherProfiles)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.ValidUntil)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.ValidUntil)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.BankData)
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.BankData)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Text1)
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.Text1)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Text2)
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.Text2)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Text3)
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.Text3)
            </dd>
        </dl>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Удалить" class="btn btn-danger" />
        </form>
    </div>
</div>

Views/Subscriptions/Details.cshtml
@model Knigosha.Core.Models.Subscription

@{
    ViewData["Title"] = "Детали абонемента";
}
<div class="container" style="margin-bottom: 30px">
    <partial name="_DashboardPartial" />

    <div id="questionDetail">
        <h4>Детали абонемента</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">
                Название:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-4">
                Тип абонемента:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.SubscriptionType)
            </dd>
            <dt class="col-sm-4">
                Цена:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.CurrentPrice)
            </dd>
            <dt class="col-sm-4">
                Старая цена:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.OldPrice)
            </dd>
            <dt class="col-sm-4">
                Скидка:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Discount)
            </dd>
            <dt class="col-sm-4">
                Количество вопросников:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.MaxQuizzes)
            </dd>
            <dt class="col-sm-4">
                Ученических профилей:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NumberOfStudentProfiles)
            </dd>
            <dt class="col-sm-4">
                Родительских профилей:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NumberOfParentProfiles)
            </dd>
            <dt class="col-sm-4">
                Учительских профилей:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NumberOfTeacherProfiles)
            </dd>
            <dt class="col-sm-4">
                Действителен до:
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.ValidUntil)
            </dd>
            <dt class="col-sm-4">
                Данные банка для перевода:
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.BankData)
            </dd>
            <dt class="col-sm-4">
                Текст 1:
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.Text1)
            </dd>
            <dt class="col-sm-4">
                Текст 2:
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.Text2)
            </dd>
            <dt class="col-sm-4">
                Текст 3:
            </dt>
            <dd class="break-word col-sm-8">
                @Html.DisplayFor(model => model.Text3)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn btn-secondary">Редактировать</a>
        <a style="margin-left: 20px" asp-action="IndexAdmin" class="btn btn btn-light">Назад</a>
    </div>
</div>

Views/Subscriptions/Edit.cshtml
@using Knigosha.Core.Models.Enums
@model Knigosha.Core.Models.Subscription

@{
    ViewData["Title"] = "Редактировать абонемент";
}
<div class="container" style="margin-bottom: 30px">
    <partial name="_DashboardPartial" />
    <div>
        <div class="header">
            <h4>Редактировать абонемент</h4>
            <a asp-action="IndexAdmin" class="btn btn btn-light ">Назад к абонементам</a>
        </div>
        <hr />
        <div class="inputAdmin row">
            <div class="col-md-12">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <select asp-for="Name" asp-items="Html.GetEnumSelectList<SubscriptionNames>()" class="form-control"><option value=""> - Выберите имя абонемента - </option></select>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SubscriptionType"></label>
                        <select asp-for="SubscriptionType" asp-items="Html.GetEnumSelectList<SubscriptionTypes>()" class="form-control"><option value=""> - Выберите тип абонемента - </option></select>
                        <span asp-validation-for="SubscriptionType" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CurrentPrice"></label>
                        <input asp-for="CurrentPrice" class="form-control" />
                        <span asp-validation-for="CurrentPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="OldPrice"></label>
                        <input asp-for="OldPrice" class="form-control" />
                        <span asp-validation-for="OldPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Discount"></label>
                        <input asp-for="Discount" class="form-control" />
                        <span asp-validation-for="Discount" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MaxQuizzes"></label>
                        <input asp-for="MaxQuizzes" class="form-control" />
                        <span asp-validation-for="MaxQuizzes" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NumberOfStudentProfiles"></label>
                        <input asp-for="NumberOfStudentProfiles" class="form-control" />
                        <span asp-validation-for="NumberOfStudentProfiles" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NumberOfParentProfiles"></label>
                        <input asp-for="NumberOfParentProfiles" class="form-control" />
                        <span asp-validation-for="NumberOfParentProfiles" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NumberOfTeacherProfiles"></label>
                        <input asp-for="NumberOfTeacherProfiles" class="form-control" />
                        <span asp-validation-for="NumberOfTeacherProfiles" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ValidUntil"></label>
                        <input asp-for="ValidUntil" class="form-control" />
                        <span asp-validation-for="ValidUntil" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BankData"></label>
                        <textarea rows="2" asp-for="BankData" class="form-control"></textarea>
                        <span asp-validation-for="BankData" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Text1"></label>
                        <textarea rows="2" asp-for="Text1" class="form-control"></textarea>
                        <span asp-validation-for="Text1" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Text2"></label>
                        <textarea rows=2 asp-for="Text2" class="form-control"></textarea>
                        <span asp-validation-for="Text2" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Text3"></label>
                        <textarea rows="2" asp-for="Text3" class="form-control"></textarea>
                        <span asp-validation-for="Text3" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Сохранить изменения" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Subscriptions/Index.cshtml
@model System.Collections.Generic.List<Knigosha.Core.Models.Subscription>

@{
    ViewData["Title"] = "Абонементы";
}

<div id="content">
    <div class="bg2">
        <div style="height:80px;"></div>
        <div class="container" id="license_types">
            <h1 class="section_title">АБОНЕМЕНТЫ</h1>
            <div class="section_text">
                Выбери подходящий абонемент.<br />
                <br />
                При регистрации профиля автоматически начинается <span style="font-weight: bold">трёхнедельный демо-период</span>. 
                Чтобы продолжить пользование после этого периода, нужно выбрать абонемент.<br />
                <br />
                Все подписки действительны до @Model[0].ValidUntil.<br />
                <br />
                <span style="font-weight: bold ">Если ты хочешь заказать более 1 абонемента одновременно и со скидкой, пиши нам по адресу info@knigovishe.ru</span>
            </div>
            <div class="row">
                <div class="col col-md-4">
                    <div class="license license1" @*onclick="window.location = '/Manage/Order'"*@ style="cursor: pointer;">
                        <div style="height: 60px;">
                            <div class="license_text">
                                <h4 style="font-size: 22px; line-height: 26px;">@Html.DisplayFor(m => m[0].Name)</h4>
                            </div>
                        </div>
                        <div class="license_center ">
                            <div class="license_text">
                                <i>Ученических профилей:</i><br><b>@Model[0].NumberOfStudentProfiles</b><div style="height: 10px;"></div>
                                <i>Действителен до:</i><br><b>@Model[0].ValidUntil</b><div style="height: 10px;"></div>
                                <i>Количество викторин:</i><br><b>@Model[0].MaxQuizzes</b>
                            </div>
                        </div>
                        <div style="height: 20px;"></div>
                        <div class="license_text license_price ">
                            <i>Цена:</i><br><b>@Model[0].CurrentPrice</b>
                        </div>
                        <div class="vote_shadow" style="display: none;" onclick="$(this).hide();event.stopPropagation();">
                            <div class="vote_popup license_popup"></div>
                        </div>
                        <div style="height: 40px;"></div>
                        <a @*asp-controller="Manage" asp-action="Order"*@  class="button">Заказать</a>
                    </div>
                    <div style="height: 50px;"></div>
                </div>
                <div class="col col-md-4">
                    <div class="license license2" @*onclick="window.location = '/Manage/Order'"*@  style="cursor:pointer;">
                        <div style="height:60px;">
                            <div class="license_text">
                                <h4 style="font-size:22px;line-height:26px;">@Html.DisplayFor(m => m[1].Name)</h4>
                            </div>
                        </div>
                        <div class="license_center ">
                            <div class="license_text">
                                <i>Родителских профилей:</i><br><b>@Model[1].NumberOfParentProfiles</b><div style="height:10px;"></div>
                                <i>Ученических профилей:</i><br><b>@Model[1].NumberOfStudentProfiles</b><div style="height:10px;"></div>
                                <i>Действителен до:</i><br><b>@Model[1].ValidUntil</b><div style="height:10px;"></div>
                                <i>Количество викторин:</i><br><b>@Model[1].MaxQuizzes</b>
                            </div>
                        </div>
                        <div style="height:20px;"></div>
                        <div class="license_text license_price "><i>Цена:</i><br><b>@Model[1].CurrentPrice</b></div>
                        <div class="vote_shadow" style="display:none;" onclick="$(this).hide();event.stopPropagation();">
                            <div class="vote_popup license_popup"></div>
                        </div>
                        <div style="height:40px;"></div>
                        <a @*asp-controller="Manage" asp-action="Order"*@ class="button">Заказать</a>
                    </div>
                    <div style="height:50px;"></div>
                </div>
                <div class="col col-md-4">
                    <div class="license license3"  @*onclick="window.location = '/Manage/Order'"*@ style="cursor:pointer;">
                        <div style="height:60px;">
                            <div class="license_text">
                                <h4 style="font-size:22px;line-height:26px;">@Html.DisplayFor(m => m[2].Name)</h4>
                            </div>
                        </div>
                        <div class="license_center ">
                            <div class="license_text">
                                <i>Учительских профилей:</i><br><b>@Model[2].NumberOfTeacherProfiles</b><div style="height:10px;"></div>
                                <i>Ученических профилей:</i><br><b>@Model[2].NumberOfStudentProfiles</b><div style="height:10px;"></div>
                                <i>Действителен до:</i><br><b>@Model[2].ValidUntil</b><div style="height:10px;"></div>
                                <i>Количество викторин:</i><br><b>@Model[2].MaxQuizzes</b>
                            </div>
                        </div>
                        <div style="height:20px;"></div>
                        <div class="license_text license_price ">
                            <i>Цена:</i><br><b>@Model[2].CurrentPrice</b>
                            <div style="height:20px;"></div>
                            <a href="javascript:;" onclick="licensePopup(this);event.stopPropagation();">Скидки при покупке от трёх абонементов</a>
                        </div>
                        <div class="vote_shadow" style="display:none;" onclick="$(this).hide();event.stopPropagation();">
                            <div class="vote_popup license_popup">
                                Дополнительные скидки при покупке нескольких классных<br />
                                абонементов одновременно:<br />
                                <br />
                                - от 3 до 5 классных абонементов – скидка 5 % <br />
                                - от 6 до 9 классных абонементов – скидка 7 % <br />
                                - от 10 до 14 классных абонементов – скидка 10 % <br />
                                - от 15 до 19 классных абонементов – скидка 12 % <br />
                                - от 20 до 24 классных абонементов – скидка 15 % <br />
                                - от 25 до 29 классных абонементов – скидка 17 % <br />
                                - от 30 до 34 классных абонементов – скидка 20 % <br />
                                - от 35 до 39 классных абонементов – скидка 25 % <br />
                                - от 40 абонементов – скидка 30 % <br />
                                <br />
                                Для информации и заявок: info@knigovishe.ru
                            </div>
                        </div>
                        <div style="height:40px;"></div>
                        <a @*asp-controller="Manage" asp-action="Order"*@ class="button">Заказать</a>
                    </div>
                    <div style="height:50px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Subscriptions/IndexAdmin.cshtml
@model IEnumerable<Knigosha.Core.Models.Subscription>

@{
    ViewData["Title"] = "Абонементы";
}
<div class="container" style="min-height: calc(100vh - 360px); margin-bottom: 30px"><partial name="_DashboardPartial" />
    <a asp-controller="Subscriptions" asp-action="Create" class="btn btn btn-light adminButton">Новый абонемент</a>
    <table class="table table-bordered adminTable">
        <thead>
        <tr>
            <th>
                Тип абонемента
            </th>
            <th>
                Цена
            </th>
            <th>
                Старая цена
            </th>
            <th>
                Действителен до
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id"> @Html.DisplayFor(modelItem => item.SubscriptionType)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OldPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValidUntil)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary btn-sm">Редактировать</a> 
                    <a asp-action="Delete" asp-route-id="@item.Id"><i id="deleteIcon" class="fa fa-trash-o"></i></a>
                </td>
            </tr>
        }
        </tbody>
    </table></div>